"""Shared canvas renderer for the price-action engine (XAU Sovereign and the STRUCT panel): candles, MAs,
Supertrend, Bollinger, order blocks, FVGs, liquidity pools, BOS/CHoCH, swing tags, signal markers,
entry/stop/target, composite score strip, pointer crosshair. `window.finoPA.draw(canvas, data, opts)`
where opts = {layers, tf, hover}; returns {geom, hoverText} for the caller's crosshair handling."""

JS = r"""
window.finoPA=(function(){
  function css(n){ return getComputedStyle(document.documentElement).getPropertyValue(n).trim()||'#fff'; }
  var C={gold:css('--gold')||'#f5c842',cyan:css('--cyan')||'#7fe0f0',pink:css('--pink')||'#ff6ec7',up:css('--up')||'#3dd68c',down:css('--down')||'#ff5c6c',faint:css('--faint')||'#6d609e',text:css('--text')||'#f1edff'};
  function nf(x,d){ if(x==null||isNaN(x)) return '—'; d=d==null?1:d; return Number(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}); }
  function ctx2d(cv){ var r=cv.getBoundingClientRect(), dpr=window.devicePixelRatio||1; var w=Math.max(200,Math.floor(r.width)), h=Math.max(120,Math.floor(r.height)); if(cv.width!==Math.floor(w*dpr)||cv.height!==Math.floor(h*dpr)){ cv.width=Math.floor(w*dpr); cv.height=Math.floor(h*dpr); } var c=cv.getContext('2d'); c.setTransform(dpr,0,0,dpr,0,0); c.clearRect(0,0,w,h); c.font='10px IBM Plex Mono,monospace'; return {c:c,w:w,h:h}; }
  function draw(cv,d,o){ if(!d||!cv||!d.series) return null; var hoverText=null; o=o||{}; o.layers=o.layers||{zones:true,liq:true,struct:true,ma:true,st:true}; var g=ctx2d(cv), c=g.c, S=d.series, n=S.t.length; var pad={l:8,r:64,t:14,b:18}; var FP=!!(o.layers.fp&&d.fp&&d.fp.has_volume&&(g.w-72)/n>=3.5); var scoreH=FP?118:70; var ph=g.h-pad.t-pad.b-scoreH-18; var pw=g.w-pad.l-pad.r; var bw=pw/n;
    var lo=Infinity, hi=-Infinity; for(var i=0;i<n;i++){ if(S.l[i]<lo) lo=S.l[i]; if(S.h[i]>hi) hi=S.h[i]; } if(d.stop){ lo=Math.min(lo,d.stop); hi=Math.max(hi,d.stop); } if(d.target){ lo=Math.min(lo,d.target); hi=Math.max(hi,d.target); } var m=(hi-lo)*.06||1; lo-=m; hi+=m;
    function sx(i){ return pad.l+i*bw+bw/2; } function sy(p){ return pad.t+(hi-p)/(hi-lo)*ph; } var y0=pad.t+ph;
    var L=o.layers, pa=d.pa||{}; var dense=bw<4.5; c.save(); c.beginPath(); c.rect(pad.l,pad.t-12,pw,ph+14); c.clip();
    c.strokeStyle='rgba(190,150,255,.07)'; for(var gi=0;gi<=5;gi++){ var gy=pad.t+ph*gi/5; c.beginPath(); c.moveTo(pad.l,gy); c.lineTo(g.w-pad.r,gy); c.stroke(); }
    if(FP){ var rows=d.fp.rows, vmax=1; rows.forEach(function(r){ r[2].forEach(function(x){ if(x>vmax) vmax=x; }); }); for(var fi=0;fi<n&&fi<rows.length;fi++){ var r=rows[fi]; if(r[1]<=r[0]) continue; var nb=r[2].length, hcell=(sy(r[0])-sy(r[1]))/nb; var buyish=r[5]>=0; for(var b=0;b<nb;b++){ var a=Math.min(.85,.08+.77*r[2][b]/vmax); c.fillStyle=buyish?'rgba(61,214,140,'+a+')':'rgba(255,92,108,'+a+')'; c.fillRect(sx(fi)-bw*.46,sy(r[0]+(b+1)*(r[1]-r[0])/nb),bw*.92,Math.max(1,hcell)); } } }
    // dealing range premium/discount
    if(L.struct&&pa.range){ var r=pa.range, mid=(r.hi+r.lo)/2; c.fillStyle='rgba(255,92,108,.05)'; c.fillRect(sx(r.i0),sy(r.hi),g.w-pad.r-sx(r.i0),sy(mid)-sy(r.hi)); c.fillStyle='rgba(61,214,140,.05)'; c.fillRect(sx(r.i0),sy(mid),g.w-pad.r-sx(r.i0),sy(r.lo)-sy(mid)); c.strokeStyle='rgba(245,200,66,.35)'; c.setLineDash([2,4]); c.beginPath(); c.moveTo(sx(r.i0),sy(mid)); c.lineTo(g.w-pad.r,sy(mid)); c.stroke(); c.setLineDash([]); c.fillStyle='rgba(245,200,66,.6)'; c.textAlign='left'; c.fillText('50% · '+(pa.structure===1?'discount below':pa.structure===-1?'premium above':''),sx(r.i0)+3,sy(mid)-3); }
    // zones
    if(L.zones){ (pa.fvgs||[]).slice(dense?-4:-8).forEach(function(f){ c.fillStyle=f.dir===1?'rgba(61,214,140,.13)':'rgba(255,92,108,.13)'; c.fillRect(sx(f.i)-bw/2,sy(f.top),g.w-pad.r-sx(f.i)+bw/2,Math.max(1,sy(f.bot)-sy(f.top))); }); (pa.obs||[]).slice(dense?-3:-6).forEach(function(o){ c.fillStyle=o.dir===1?'rgba(106,53,240,.28)':'rgba(255,110,199,.22)'; c.fillRect(sx(o.i)-bw/2,sy(o.top),g.w-pad.r-sx(o.i)+bw/2,Math.max(1,sy(o.bot)-sy(o.top))); c.fillStyle=o.dir===1?'rgba(170,140,255,.9)':'rgba(255,150,220,.9)'; c.textAlign='left'; c.fillText(o.dir===1?'OB demand':'OB supply',sx(o.i)+2,sy(o.top)-2); }); }
    // liquidity pools
    if(L.liq){ (pa.pools||[]).slice(dense?-5:-10).forEach(function(p){ var end=p.swept&&p.swept>0?sx(p.swept):g.w-pad.r; c.strokeStyle=p.type==='EQH'?'rgba(255,92,108,.7)':'rgba(61,214,140,.7)'; c.setLineDash([4,3]); c.beginPath(); c.moveTo(sx(p.i0),sy(p.price)); c.lineTo(end,sy(p.price)); c.stroke(); c.setLineDash([]); c.fillStyle=p.type==='EQH'?'rgba(255,92,108,.9)':'rgba(61,214,140,.9)'; c.textAlign='left'; c.fillText(p.type+(p.swept&&p.swept>0?' swept':''),sx(p.i0)+2,sy(p.price)+(p.type==='EQH'?-3:10)); if(p.swept&&p.swept>0){ c.font='bold 11px IBM Plex Mono,monospace'; c.fillText('×',end-3,sy(p.price)+4); c.font='10px IBM Plex Mono,monospace'; } }); }
    // MAs and bands
    function line(arr,color,dash,w){ c.strokeStyle=color; c.lineWidth=w||1; if(dash) c.setLineDash(dash); c.beginPath(); var on=false; for(var i=0;i<n;i++){ if(arr[i]==null){ on=false; continue; } if(!on){ c.moveTo(sx(i),sy(arr[i])); on=true; } else c.lineTo(sx(i),sy(arr[i])); } c.stroke(); c.setLineDash([]); c.lineWidth=1; }
    if(L.ma){ line(S.bb_up,'rgba(190,150,255,.18)'); line(S.bb_lo,'rgba(190,150,255,.18)'); line(S.e21,C.cyan,null,1); line(S.e50,C.gold,null,1); line(S.s200,'rgba(168,156,207,.8)',[6,4],1.2); }
    if(L.st){ for(var i=1;i<n;i++){ if(S.st[i]==null||S.st[i-1]==null||S.st_dir[i]!==S.st_dir[i-1]) continue; c.strokeStyle=S.st_dir[i]===1?'rgba(61,214,140,.9)':'rgba(255,92,108,.9)'; c.lineWidth=1.4; c.beginPath(); c.moveTo(sx(i-1),sy(S.st[i-1])); c.lineTo(sx(i),sy(S.st[i])); c.stroke(); } c.lineWidth=1; }
    // candles
    var cw=Math.max(1,bw*.62); for(var i=0;i<n;i++){ var up=S.c[i]>=S.o[i]; c.strokeStyle=up?C.up:C.down; c.fillStyle=up?C.up:C.down; c.beginPath(); c.moveTo(sx(i),sy(S.h[i])); c.lineTo(sx(i),sy(S.l[i])); c.stroke(); var top=sy(Math.max(S.o[i],S.c[i])), hgt=Math.max(1,Math.abs(sy(S.o[i])-sy(S.c[i]))); c.fillRect(sx(i)-cw/2,top,cw,hgt); }
    if(o.layers.vp&&d.profile){ var P=d.profile, pmax=Math.max.apply(null,P.vol)||1, pwid=pw*.2; for(var bi=0;bi<P.buckets;bi++){ var blo=P.lo+bi*P.size, bhi=blo+P.size; var wpx=pwid*P.vol[bi]/pmax; var isPoc=Math.abs((blo+bhi)/2-P.poc)<P.size*.51; var inVA=bhi>P.val-1e-9&&blo<P.vah+1e-9; c.fillStyle=isPoc?'rgba(245,200,66,.55)':inVA?'rgba(127,224,240,.28)':'rgba(127,224,240,.12)'; c.fillRect(g.w-pad.r-wpx,sy(bhi),wpx,Math.max(1,sy(blo)-sy(bhi)-1)); } c.strokeStyle='rgba(245,200,66,.8)'; c.setLineDash([3,3]); c.beginPath(); c.moveTo(pad.l,sy(P.poc)); c.lineTo(g.w-pad.r,sy(P.poc)); c.stroke(); c.setLineDash([]); c.fillStyle=C.gold; c.textAlign='right'; c.fillText('POC '+nf(P.poc,0),g.w-pad.r-4,sy(P.poc)-3); c.fillStyle='rgba(127,224,240,.9)'; c.fillText('VA '+nf(P.val,0)+'–'+nf(P.vah,0),g.w-pad.r-4,pad.t+ph-4); }
    // structure: swings + breaks
    if(L.struct){ c.font='9px IBM Plex Mono,monospace'; (pa.swings||[]).slice(dense?-14:-40).forEach(function(s){ if(s.i<0||s.i>=n) return; c.fillStyle=s.type==='high'?'rgba(255,92,108,.85)':'rgba(61,214,140,.85)'; c.textAlign='center'; c.fillText(s.tag,sx(s.i),s.type==='high'?sy(s.price)-4:sy(s.price)+11); }); (pa.events||[]).slice(dense?-6:-14).forEach(function(e){ if(e.i<0||e.i>=n) return; var col=e.type==='CHoCH'?C.gold:(e.dir===1?C.up:C.down); c.strokeStyle=col; c.setLineDash([3,2]); c.beginPath(); c.moveTo(sx(e.from),sy(e.level)); c.lineTo(sx(e.i),sy(e.level)); c.stroke(); c.setLineDash([]); c.fillStyle=col; c.textAlign='center'; c.fillText(e.type,sx((e.from+e.i)/2),e.dir===1?sy(e.level)-4:sy(e.level)+11); }); c.font='10px IBM Plex Mono,monospace'; }
    // signal markers
    (d.markers||[]).forEach(function(mk){ var i=mk.i; if(i<0||i>=n) return; c.textAlign='center'; if(mk.side==='BUY'){ c.fillStyle=C.up; c.font='bold 13px IBM Plex Mono,monospace'; c.fillText('▲',sx(i),sy(S.l[i])+14); c.font='9px IBM Plex Mono,monospace'; c.fillText(mk.label||'BUY',sx(i),sy(S.l[i])+24); } else if(mk.side==='SELL'){ c.fillStyle=C.down; c.font='bold 13px IBM Plex Mono,monospace'; c.fillText('▼',sx(i),sy(S.h[i])-6); c.font='9px IBM Plex Mono,monospace'; c.fillText(mk.label||'SELL',sx(i),sy(S.h[i])-16); } else { c.fillStyle='rgba(168,156,207,.9)'; c.font='11px IBM Plex Mono,monospace'; c.fillText('×',sx(i),sy(S.h[i])-6); } c.font='10px IBM Plex Mono,monospace'; });
    c.restore();
    // levels on the right
    function level(p,color,txt,dash){ if(p==null) return; c.strokeStyle=color; if(dash) c.setLineDash(dash); c.beginPath(); c.moveTo(pad.l,sy(p)); c.lineTo(g.w-pad.r,sy(p)); c.stroke(); c.setLineDash([]); c.fillStyle=color; c.fillRect(g.w-pad.r+1,sy(p)-7,pad.r-2,14); c.fillStyle='#0c0626'; c.textAlign='left'; c.fillText(txt,g.w-pad.r+4,sy(p)+4); }
    level(d.entry,C.cyan,nf(d.entry,0),[1,3]); level(d.stop,C.down,'SL '+nf(d.stop,0),[4,3]); level(d.target,C.up,'T '+nf(d.target,0),[4,3]); (d.levels||[]).forEach(function(lv){ level(lv.price,lv.color==='down'?C.down:lv.color==='up'?C.up:C.gold,lv.label,[4,3]); });
    if(d.legend){ c.font='9px IBM Plex Mono,monospace'; var lx=pad.l+4; [['e21',C.cyan],['e50',C.gold],['s200','rgba(168,156,207,.9)']].forEach(function(k){ if(!d.legend[k[0]]) return; c.fillStyle=k[1]; c.textAlign='left'; c.fillText(d.legend[k[0]],lx,pad.t-3); lx+=c.measureText(d.legend[k[0]]).width+12; }); c.font='10px IBM Plex Mono,monospace'; }
    // price axis
    c.fillStyle=C.faint; c.textAlign='left'; for(var k=0;k<=5;k++){ var v=lo+(hi-lo)*k/5; if(Math.abs(sy(v)-sy(d.entry))<9||(d.stop&&Math.abs(sy(v)-sy(d.stop))<9)||(d.target&&Math.abs(sy(v)-sy(d.target))<9)) continue; c.fillText(nf(v,0),g.w-pad.r+4,sy(v)+3); }
    // time axis
    c.textAlign='center'; var step=Math.max(1,Math.round(n/Math.max(3,Math.floor(pw/((o.tf==='1d'||o.tf==='D')?70:110))))); for(var i=0;i<n;i+=step){ var dt=new Date(S.t[i]); c.fillText((o.tf==='1d'||o.tf==='D')?dt.toLocaleDateString('en-GB',{day:'2-digit',month:'short'}):dt.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})+' '+dt.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}),sx(i),y0+13); }
    // score strip
    var scoreArea=FP?60:scoreH; var sy0=y0+18+scoreArea/2, sh=scoreArea/2-4; c.strokeStyle='rgba(190,150,255,.14)'; c.beginPath(); c.moveTo(pad.l,sy0); c.lineTo(g.w-pad.r,sy0); c.stroke(); c.strokeStyle='rgba(255,255,255,.12)'; c.setLineDash([2,3]); c.beginPath(); c.moveTo(pad.l,sy0-sh*.25); c.lineTo(g.w-pad.r,sy0-sh*.25); c.moveTo(pad.l,sy0+sh*.25); c.lineTo(g.w-pad.r,sy0+sh*.25); c.stroke(); c.setLineDash([]);
    for(var i=0;i<n;i++){ var v=S.score[i]; if(v==null) continue; c.fillStyle=S.state[i]===1?'rgba(61,214,140,.85)':S.state[i]===-1?'rgba(255,92,108,.85)':'rgba(168,156,207,.5)'; var hh=v*sh; c.fillRect(sx(i)-cw/2,Math.min(sy0,sy0-hh),cw,Math.abs(hh)||1); }
    c.fillStyle=C.faint; c.textAlign='left'; c.fillText((d.engine==='seller'?'sell score':d.engine==='scalp'?'trend score':'composite score')+'  +1',pad.l+2,y0+27); c.fillText('−1',pad.l+2,y0+18+scoreArea-2);
    if(FP){ var dy0=y0+18+scoreArea+4, dh=scoreH-scoreArea-8, dmid=dy0+dh/2, dmax=1; d.fp.rows.forEach(function(r){ if(Math.abs(r[5])>dmax) dmax=Math.abs(r[5]); }); var cvd=d.fp.cvd, cmin=Math.min.apply(null,cvd), cmax=Math.max.apply(null,cvd); c.strokeStyle='rgba(190,150,255,.14)'; c.beginPath(); c.moveTo(pad.l,dmid); c.lineTo(g.w-pad.r,dmid); c.stroke(); for(var di=0;di<n&&di<d.fp.rows.length;di++){ var dv=d.fp.rows[di][5]; c.fillStyle=dv>=0?'rgba(61,214,140,.7)':'rgba(255,92,108,.7)'; var dhh=dv/dmax*(dh/2-2); c.fillRect(sx(di)-cw/2,Math.min(dmid,dmid-dhh),cw,Math.abs(dhh)||1); } if(cmax>cmin){ c.strokeStyle=C.gold; c.lineWidth=1.4; c.beginPath(); for(var ci=0;ci<n&&ci<cvd.length;ci++){ var cy=dy0+2+(cmax-cvd[ci])/(cmax-cmin)*(dh-4); ci===0?c.moveTo(sx(ci),cy):c.lineTo(sx(ci),cy); } c.stroke(); c.lineWidth=1; } c.fillStyle=C.faint; c.textAlign='left'; c.fillText('volume delta · CVD (gold)',pad.l+2,dy0+10); }
    // hover
    if(o.hover!=null&&o.hover>=0&&o.hover<n){ var i=o.hover; c.strokeStyle='rgba(245,200,66,.45)'; c.beginPath(); c.moveTo(sx(i),pad.t); c.lineTo(sx(i),g.h-pad.b); c.stroke(); var dt=new Date(S.t[i]); hoverText=dt.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})+(!(o.tf==='1d'||o.tf==='D')?' '+dt.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}):'')+'  O '+nf(S.o[i],1)+'  H '+nf(S.h[i],1)+'  L '+nf(S.l[i],1)+'  C '+nf(S.c[i],1)+'  score '+(S.score[i]==null?'—':(S.score[i]>=0?'+':'')+nf(S.score[i],2))+'  '+(S.state[i]===1?'BUY':S.state[i]===-1?'SELL':'neutral'); }
    return {geom:{pad:pad,bw:bw,n:n},hoverText:hoverText}; }
  return {draw:draw};
})();
"""
