"""Terminal panels RISK (whole-book risk board) and OISCAN (OI build-up screener): markup, CSS and a
self-contained script that pages.py splices into the dashboard. Charts are canvas in the terminal
palette; nothing animates on its own."""

HEAT_MARKUP = r"""
  <section class="panel a-wide an" id="p-heat" aria-label="Market heatmap">
    <div class="panel-hd"><span class="k">HEAT</span><span class="s" id="ht-title">MARKET HEATMAP · F&amp;O STOCKS · TOP 20 GAINERS · TOP 20 LOSERS</span><span class="r"><span class="an-state" id="ht-state">—</span></span></div>
    <div class="stx-top"><span class="seg" id="ht-u"><button type="button" data-u="n50">NIFTY 50</button><button type="button" data-u="fo" class="on">F&amp;O</button><button type="button" data-u="all">ALL NSE</button></span>
      <span class="seg" id="ht-mode"><button type="button" data-m="top" class="on">TOP 20 · 20</button><button type="button" data-m="all">ALL</button><button type="button" data-m="gainers">GAINERS</button><button type="button" data-m="losers">LOSERS</button></span>
      <span class="seg" id="ht-size"><button type="button" data-z="move" class="on">SIZE BY MOVE</button><button type="button" data-z="flat">UNIFORM</button></span>
      <label class="an-lbl">FIND <input class="an-in" id="ht-q" placeholder="symbol" maxlength="20" style="width:110px;text-transform:uppercase" aria-label="Filter symbols"></label>
      <span class="an-note" id="ht-note">click a tile to chart it</span></div>
    <div class="an-kpi" id="ht-kpi"></div>
    <div class="ht-map" id="ht-map"></div>
    <div class="an-foot">Live through the session (refreshes every 10 seconds while the market is open, then holds the close). Default view: the 20 top gainers and 20 top losers of the chosen universe, coloured by today's change versus the previous close — deeper green and red for bigger moves, tile size by the size of the move. ALL tiles every name (ALL NSE: the 400 biggest movers among 6,900 listed). F&amp;O = the 200+ stocks with options. Click any tile to load it in the CHART panel; type a symbol to find it.</div>
  </section>
"""

MARKUP = r"""
  <section class="panel a-wide an" id="p-risk" aria-label="Risk board">
    <div class="panel-hd"><span class="k">RISK</span><span class="s">RISK BOARD · WHOLE BOOK · ₹ GREEKS · SHOCKS · LIMITS</span><span class="r"><span class="an-state" id="rk-state">—</span></span></div>
    <div class="an-kpi" id="rk-kpi"></div>
    <div class="rk-breach" id="rk-breach" hidden></div>
    <div class="rk-grid">
      <div><h5>BY UNDERLYING · HEDGE TO FLAT</h5><div class="scroll rk-tbl"><table class="an-table"><thead><tr><th>UNDERLYING</th><th>SPOT · DAY</th><th>POS · LOTS</th><th>Δ ₹/1%</th><th>Γ ₹/1%</th><th>VEGA /pt</th><th>THETA /day</th><th>HEDGE</th></tr></thead><tbody id="rk-u"></tbody></table></div></div>
      <div><h5>BY EXPIRY · PAYOFF AT EXPIRY (±6%)</h5><div class="scroll rk-tbl"><table class="an-table"><thead><tr><th>UNDERLYING</th><th>EXPIRY</th><th>DTE</th><th>Δ ₹/1%</th><th>VEGA</th><th>THETA</th><th>MAX LOSS</th><th>MAX PROFIT</th><th>BREAKEVENS</th></tr></thead><tbody id="rk-e"></tbody></table></div></div>
    </div>
    <div class="an-top"><span class="seg" id="rk-day"><button type="button" data-d="0" class="on">TODAY</button><button type="button" data-d="1">TOMORROW</button></span><span class="an-note">book P&amp;L vs now for a spot shift (columns) × IV shift (rows) · worst cell boxed in gold</span></div>
    <div class="an-cvw" style="height:200px"><canvas class="an-cv" id="rk-cv"></canvas></div>
    <div class="rk-limits" id="rk-limits"></div>
    <div class="an-foot">Every open position — paper, ALGO and your connected broker — priced off the live chains. ₹ Greeks: Δ ₹/1% is the P&amp;L of a 1% spot move, Γ ₹/1% the extra P&amp;L from convexity over that move, vega per 1 IV point, theta per calendar day. Hedge = futures lots that flatten delta (or the ATM-option equivalent at ~0.5Δ). Limits are yours; breaches show in red.</div>
  </section>
  <section class="panel an" id="p-move" aria-label="Expected versus realised move">
    <div class="panel-hd"><span class="k">MOVE</span><span class="s">EXPECTED vs REALISED · TODAY</span><span class="r"><span class="an-state" id="mv-state">—</span></span></div>
    <div class="an-top"><span class="seg" id="mv-u"><button type="button" data-u="NIFTY 50" class="on">NIFTY</button><button type="button" data-u="BANKNIFTY">BANKNIFTY</button><button type="button" data-u="FINNIFTY">FINNIFTY</button><button type="button" data-u="SENSEX">SENSEX</button></span><span class="an-note" id="mv-note">—</span></div>
    <div class="an-kpi" id="mv-kpi"></div>
    <div class="an-cvw" style="height:210px"><canvas class="an-cv" id="mv-cv"></canvas></div>
    <div class="an-foot">Expected day move = spot × ATM IV × √(1/252), a 1σ band around the previous close (shaded). Realised = today's high–low range against the 2σ-wide expected range, and the move from the previous close in sigmas. The straddle figure is what the market charges for the move to expiry. Refreshes every 30 s.</div>
  </section>
  <section class="panel a-wide an vipx" id="p-struct" aria-label="VIP engines">
    <div class="panel-hd"><span class="k">VIP</span><span class="s" id="stx-title">VIP INDICATOR · STRUCTURE · NIFTY 15M</span><span class="r"><a id="stx-pine" href="/vip-indicator/pine" hidden style="color:var(--gold);border:1px solid var(--gold);padding:1px 7px;font-size:9.5px;letter-spacing:.1em">PINE ↓</a><span class="an-state" id="stx-state">—</span></span></div>
    <div class="stx-top">
      <span class="stx-eng" id="stx-eng"><button type="button" data-e="struct" class="on">STRUCTURE</button><button type="button" data-e="scalp">SCALPER</button><button type="button" data-e="seller">SELLER</button></span>
      <span class="seg an-u" id="stx-u"><button type="button" data-u="NIFTY 50" class="on">NIFTY</button><button type="button" data-u="BANKNIFTY">BANKNIFTY</button><button type="button" data-u="FINNIFTY">FINNIFTY</button><button type="button" data-u="SENSEX">SENSEX</button></span>
      <label class="an-lbl">STOCK <input class="an-in" id="stx-sym" placeholder="RELIANCE" maxlength="20" style="width:96px" aria-label="F&amp;O stock symbol"></label>
      <span class="seg" id="stx-tf"><button type="button" data-tf="5m">5M</button><button type="button" data-tf="15m" class="on">15M</button><button type="button" data-tf="1h">1H</button><button type="button" data-tf="D">1D</button></span>
      <span class="seg" id="stx-layers"><button type="button" data-l="zones" class="on">ZONES</button><button type="button" data-l="liq" class="on">LIQUIDITY</button><button type="button" data-l="struct" class="on">STRUCTURE</button><button type="button" data-l="ma">MA</button><button type="button" data-l="st">SUPERTREND</button><button type="button" data-l="fp" class="on">FOOTPRINT</button><button type="button" data-l="vp" class="on">PROFILE</button></span>
      <span class="an-note" id="stx-note">move the pointer over the chart to read a bar</span></div>
    <div class="gd-sig" id="stx-sig"></div>
    <div class="an-kpi" id="stx-kpi"></div>
    <div class="an-cvw" style="height:520px;cursor:crosshair"><canvas class="an-cv" id="stx-cv"></canvas></div>
    <div class="gd-sys" id="stx-sys" style="display:grid;grid-template-columns:1fr 1fr;border-top:1px solid var(--line)"></div>
    <div class="an-foot" id="stx-foot">STRUCTURE: the XAU Sovereign engine on Indian underlyings — market structure from confirmed swings (BOS continues, CHoCH flips), order blocks (violet / pink), fair value gaps (green / red), equal highs and lows as liquidity with sweep marks, the dealing range's 50%, displacement and rejection candles — blended 50/50 with the classic systems into the score strip. FOOTPRINT: each bar's volume split into buying and selling by where it closed in its range, spread over price bins (bid/ask ticks are not in the feed, so this is the OHLCV-derived footprint), with per-bar delta and cumulative delta below the score. PROFILE: volume by price for the visible window with the point of control and 70% value area. Non-repainting. Candles from Upstox.</div>
  </section>
  <section class="panel a-wide an" id="p-ivp" aria-label="Straddle and IV percentile history">
    <div class="panel-hd"><span class="k">IVP</span><span class="s">STRADDLE &amp; IV PERCENTILE · TODAY vs THE LAST 20 CYCLES AT THIS DTE</span><span class="r"><span class="an-state" id="ivp-state">—</span></span></div>
    <div class="an-top"><span class="seg" id="ivp-u"><button type="button" data-u="NIFTY 50" class="on">NIFTY</button><button type="button" data-u="BANKNIFTY">BANKNIFTY</button><button type="button" data-u="FINNIFTY">FINNIFTY</button><button type="button" data-u="SENSEX">SENSEX</button></span><span class="an-note" id="ivp-note">first load pulls two candle files per past cycle; later loads are instant</span></div>
    <div class="an-kpi" id="ivp-kpi"></div>
    <div class="an-split"><div class="an-cvw"><canvas class="an-cv" id="ivp-cv"></canvas></div>
      <div class="scroll an-tbl-wrap"><table class="an-table"><thead><tr><th>EXPIRY</th><th>DAY</th><th>ATM</th><th>OPEN %</th><th>CLOSE %</th><th>DECAY</th></tr></thead><tbody id="ivp-rows"></tbody></table></div></div>
    <div class="an-foot">ATM straddle as % of spot through the day: today in cyan against the same clock time on past cycles at the same distance to expiry (violet, ATM fixed at each day's open; gold = median, shaded = min–max). Percentiles rank today's straddle and its implied vol against those cycles at the current minute. VIX rank = where India VIX sits in its 1-year range.</div>
  </section>
  <section class="panel a-wide an" id="p-oiscan" aria-label="OI build-up screener">
    <div class="panel-hd"><span class="k">OISCAN</span><span class="s">OI BUILD-UP SCREENER · NEAREST EXPIRY</span><span class="r"><span class="an-state" id="oi-state">—</span></span></div>
    <div class="an-top"><span class="seg" id="oi-u"><button type="button" data-u="NIFTY 50" class="on">NIFTY</button><button type="button" data-u="BANKNIFTY">BANKNIFTY</button><button type="button" data-u="FINNIFTY">FINNIFTY</button><button type="button" data-u="SENSEX">SENSEX</button></span>
      <span class="seg" id="oi-w"><button type="button" data-w="5">5 MIN</button><button type="button" data-w="15" class="on">15 MIN</button><button type="button" data-w="60">60 MIN</button><button type="button" data-w="day">DAY</button></span>
      <span class="an-note" id="oi-note">OI sampled every 3 minutes in session · tags: price↑OI↑ long build-up · price↓OI↑ short build-up · price↑OI↓ short covering · price↓OI↓ long unwinding</span></div>
    <div class="an-kpi" id="oi-kpi"></div>
    <div class="oi-read" id="oi-read">—</div>
    <div class="an-split"><div class="an-cvw"><canvas class="an-cv" id="oi-cv"></canvas></div>
      <div class="scroll an-tbl-wrap"><table class="an-table"><thead><tr><th>STRIKE</th><th>SIDE</th><th>OI</th><th>Δ OI</th><th>Δ PX</th><th>TAG</th></tr></thead><tbody id="oi-rows"></tbody></table></div></div>
    <div class="an-top" style="border-top:1px solid var(--line)"><b style="color:var(--gold);font-size:10.5px;letter-spacing:.1em">F&amp;O STOCKS · DAY BASIS</b><span class="an-note" id="oi-snote">total option OI change vs previous close against the spot move since the first sample · refreshed every 15 min</span></div>
    <div class="scroll rk-tbl" style="max-height:260px"><table class="an-table"><thead><tr><th>STOCK</th><th>SPOT</th><th>CHG</th><th>Δ OI %</th><th>CALL Δ OI</th><th>PUT Δ OI</th><th>PCR</th><th>TAG</th></tr></thead><tbody id="oi-stocks"></tbody></table></div>
    <div class="an-foot">Index chains from Upstox REST every 3 minutes during the session, kept for the day. Δ OI over the chosen window; DAY = versus previous close. The read weighs call and put writing/covering near the money: call writing above spot is supply, put writing below is support, writers covering is fuel for a move. Stocks: NIFTY 50 F&amp;O names, nearest expiry.</div>
  </section>
"""

CSS = r"""
.rk-breach{margin:0;padding:7px 10px;border-bottom:1px solid var(--line);background:rgba(255,92,108,.08);color:var(--down);font-size:11px;line-height:1.5}.rk-breach b{letter-spacing:.1em;font-size:10px}
.rk-grid{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid var(--line)}.rk-grid>div{min-width:0}.rk-grid>div:first-child{border-right:1px solid var(--line)}
.rk-grid h5{font-size:9.5px;letter-spacing:.14em;color:var(--faint);padding:6px 10px 2px;text-transform:uppercase}
.rk-tbl{max-height:200px;flex:0 0 auto}.rk-tbl td.hedge{color:var(--gold);white-space:nowrap}.rk-tbl td.src{color:var(--faint);font-size:9.5px}
.rk-limits{display:flex;gap:10px;flex-wrap:wrap;align-items:flex-end;padding:8px 10px;border-top:1px solid var(--line);font-size:10.5px}
.rk-limits label{display:flex;flex-direction:column;gap:3px;color:var(--faint);letter-spacing:.08em;font-size:9.5px}.rk-limits input{width:110px;background:#06031a;border:1px solid var(--line-strong);color:var(--text);font:inherit;font-size:11px;padding:3px 6px}.rk-limits input.bad{border-color:var(--down);color:var(--down)}
.rk-limits button{font-size:10px;letter-spacing:.1em;padding:5px 11px;border:1px solid var(--gold);color:var(--gold);background:none;cursor:pointer}.rk-limits button:hover{background:var(--gold);color:#2a1a02}.rk-limits .msg{color:var(--faint);margin-left:auto}
.oi-read{padding:6px 10px;border-bottom:1px solid var(--line);font-size:11.5px;color:var(--text)}.oi-read b{letter-spacing:.1em;font-size:10px;padding:1px 6px;border:1px solid var(--line-strong);margin-right:8px}.oi-read b.bullish{color:var(--up);border-color:var(--up)}.oi-read b.bearish{color:var(--down);border-color:var(--down)}.oi-read b.balanced,.oi-read b.quiet{color:var(--muted)}
.tag{font-size:9.5px;letter-spacing:.08em;padding:1px 5px;border:1px solid var(--line-strong);white-space:nowrap}.tag.lb{color:var(--up);border-color:var(--up)}.tag.sb{color:var(--down);border-color:var(--down)}.tag.sc{color:var(--cyan);border-color:var(--cyan)}.tag.lu{color:var(--pink);border-color:var(--pink)}.tag.flat{color:var(--faint)}
.vipx{background:linear-gradient(180deg,#130b36,#0e0729 60%,#0c0626)}
.stx-top{display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:8px 10px;border-bottom:1px solid var(--line);font-size:10.5px}
.stx-eng{display:inline-flex;border:1px solid var(--gold);padding:2px;gap:2px;background:rgba(245,200,66,.06)}.stx-eng button{font-size:10px;letter-spacing:.12em;padding:5px 12px;border:0;color:var(--muted);background:none;cursor:pointer;font-weight:600}.stx-eng button.on{background:linear-gradient(180deg,var(--gold-2),#f2b830);color:#2a1a02}
.stx-top .seg button{font-size:10px;letter-spacing:.08em;padding:4px 9px;border:1px solid var(--line-strong);color:var(--muted);background:none;cursor:pointer}.stx-top .seg button.on{background:var(--gold);color:#2a1a02;border-color:var(--gold);font-weight:600}
.gd-sig{display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center;padding:10px 12px;border-bottom:1px solid var(--line)}
.gd-sig .lbl{font-family:var(--display);font-size:38px;line-height:.9;font-weight:700;letter-spacing:.02em}.gd-sig .lbl.buy{color:var(--up)}.gd-sig .lbl.sell{color:var(--down)}.gd-sig .lbl.neutral{color:var(--muted)}
.gd-sig .meter{position:relative;height:10px;background:linear-gradient(90deg,rgba(255,92,108,.55),rgba(255,92,108,.12) 40%,rgba(120,100,160,.25) 50%,rgba(61,214,140,.12) 60%,rgba(61,214,140,.55));border:1px solid var(--line-strong)}
.gd-sig .meter i{position:absolute;top:-5px;width:3px;height:18px;background:var(--gold);box-shadow:0 0 8px var(--gold)}.gd-sig .meter b{position:absolute;top:-16px;font-size:9px;letter-spacing:.1em;color:var(--faint)}.gd-sig .meter b.l{left:0}.gd-sig .meter b.m{left:50%;transform:translateX(-50%)}.gd-sig .meter b.r{right:0}
.gd-sig .sub{font-size:10.5px;color:var(--muted);margin-top:4px;line-height:1.5}.gd-sig .sub b{color:var(--text);font-weight:500}
.gd-sig .conf{font-size:9.5px;letter-spacing:.14em;padding:3px 8px;border:1px solid var(--line-strong);color:var(--muted);text-align:center}.gd-sig .conf.ok{color:var(--up);border-color:var(--up)}.gd-sig .conf.bad{color:var(--down);border-color:var(--down)}.gd-sig .conf.mid{color:var(--gold);border-color:var(--gold)}
@media(max-width:980px){.gd-sig{grid-template-columns:1fr}}
.ht-map{display:flex;flex-wrap:wrap;gap:3px;padding:8px;align-content:flex-start;flex:1;min-height:320px;max-height:640px;overflow-y:auto;scrollbar-width:thin;scrollbar-color:var(--line-strong) transparent}
.ht-t{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff;cursor:pointer;border:1px solid rgba(0,0,0,.35);font-family:var(--mono);line-height:1.15;text-align:center;padding:2px 4px;min-width:0}.ht-t b{font-weight:700;letter-spacing:.02em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}.ht-t i{font-style:normal;opacity:.9;white-space:nowrap}
.ht-t:hover{outline:2px solid var(--gold);outline-offset:-2px;z-index:2}.ht-t.dim{opacity:.18}
.gd-sys h5{font-size:9.5px;letter-spacing:.14em;color:var(--faint);padding:6px 10px 2px;text-transform:uppercase}.gd-sys h5 i{font-style:normal;color:var(--gold);margin-left:8px}
.gd-sys>div{min-width:0}.gd-sys>div:first-child{border-right:1px solid var(--line)}.gd-sys table td{padding:4px 8px;font-size:10.5px;text-align:left;vertical-align:top}.gd-sys td.v{font-weight:600;white-space:nowrap;width:44px}.gd-sys td.v.up{color:var(--up)}.gd-sys td.v.down{color:var(--down)}.gd-sys td.v.z{color:var(--faint)}
.gd-sys td.n{white-space:nowrap;color:var(--text)}.gd-sys td.n small{display:block;color:var(--faint);font-size:9.5px}.gd-sys td.note{color:var(--muted)}
@media(max-width:980px){#stx-sys{grid-template-columns:1fr!important}#stx-sys>div:first-child{border-right:0;border-bottom:1px solid var(--line)}}
@media(max-width:980px){.rk-grid{grid-template-columns:1fr}.rk-grid>div:first-child{border-right:0;border-bottom:1px solid var(--line)}}
"""

JS = r"""
(function(){
  function $(id){ return document.getElementById(id); }
  function css(n){ return getComputedStyle(document.documentElement).getPropertyValue(n).trim()||'#fff'; }
  var C={gold:css('--gold'),cyan:css('--cyan'),pink:css('--pink'),up:css('--up'),down:css('--down'),faint:css('--faint'),text:css('--text')};
  function nf(x,d){ if(x==null||isNaN(x)) return '—'; d=d==null?0:d; return Number(x).toLocaleString('en-IN',{minimumFractionDigits:d,maximumFractionDigits:d}); }
  function inr(x){ if(x==null||isNaN(x)) return '—'; var a=Math.abs(x); var s=a>=1e7?(a/1e7).toFixed(2)+' cr':a>=1e5?(a/1e5).toFixed(2)+' L':nf(a,0); return (x<0?'−':'')+'₹'+s; }
  function sg(x,d){ if(x==null||isNaN(x)) return '—'; return (x>0?'+':'')+nf(x,d); }
  function ctx2d(cv){ var r=cv.getBoundingClientRect(), dpr=window.devicePixelRatio||1; var w=Math.max(200,Math.floor(r.width)), h=Math.max(120,Math.floor(r.height)); if(cv.width!==Math.floor(w*dpr)||cv.height!==Math.floor(h*dpr)){ cv.width=Math.floor(w*dpr); cv.height=Math.floor(h*dpr); } var c=cv.getContext('2d'); c.setTransform(dpr,0,0,dpr,0,0); c.clearRect(0,0,w,h); c.font='10px IBM Plex Mono,monospace'; return {c:c,w:w,h:h}; }
  function kpi(el,items){ el.innerHTML=items.map(function(k){ return '<div><small>'+k[0]+'</small><b'+(k[2]?' class="'+k[2]+'"':'')+'>'+k[1]+'</b></div>'; }).join(''); }
  function state(id,txt,cls){ var e=$(id); if(!e) return; e.textContent=txt; e.className='an-state'+(cls?' '+cls:''); }
  function getJSON(url,ok,fail){ fetch(url,{credentials:'same-origin'}).then(function(r){ return r.json().then(function(j){ return {s:r.status,j:j}; }); }).then(function(x){ if(x.s>=400){ fail(x.j&&x.j.error?x.j.error:(x.s===402?'Desk plan required':'HTTP '+x.s)); } else ok(x.j); }).catch(function(){ fail('network'); }); }
  function postJSON(url,body,ok,fail){ fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Requested-With':'fetch'},body:JSON.stringify(body)}).then(function(r){ return r.json().then(function(j){ return {s:r.status,j:j}; }); }).then(function(x){ if(x.s>=400){ fail(x.j&&x.j.error?x.j.error:'HTTP '+x.s); } else ok(x.j); }).catch(function(){ fail('network'); }); }
  function segInit(el,attr,onChange){ if(!el) return; el.addEventListener('click',function(e){ var b=e.target.closest('button'); if(!b) return; Array.prototype.forEach.call(el.querySelectorAll('button'),function(x){ x.classList.toggle('on',x===b); }); onChange(b.getAttribute(attr)); }); }
  function visible(id){ var el=$(id); return el&&!el.hidden&&!document.hidden; }
  function expLabel(ms){ var d=new Date(ms); return d.toLocaleDateString('en-IN',{day:'2-digit',month:'short'}); }
  var LIMIT_LABELS={delta_inr_1pct:'MAX |Δ| ₹ PER 1%',gamma_inr_1pct:'MAX |Γ| ₹ PER 1%',vega:'MAX |VEGA| ₹/pt',theta:'MAX |THETA| ₹/day',day_loss:'DAY LOSS STOP ₹'};

  /* ---------- RISK ---------- */
  var rk={data:null,day:'0'}, rkPanel=$('p-risk');
  segInit($('rk-day'),'data-d',function(d){ rk.day=d; drawRisk(); });
  function loadRisk(){ if(!rkPanel||window.FINO_LOCKED) return; getJSON('/api/risk',function(d){ rk.data=d; renderRisk(d); drawRisk(); state('rk-state',(d.positions?d.positions+' POSITIONS':'NO POSITIONS')+(d.unpriced?' · '+d.unpriced+' unpriced':'')+(d.margin?' · MARGIN LIVE':''),d.breaches&&d.breaches.length?'err':'ok'); },function(e){ state('rk-state',e,'err'); }); }
  function renderRisk(d){ var i=d.inr||{}, m=d.margin;
    kpi($('rk-kpi'),[['net Δ ₹ / 1%',inr(i.delta_inr_1pct),i.delta_inr_1pct>=0?'up':'down'],['Γ ₹ / 1%',inr(i.gamma_inr_1pct),i.gamma_inr_1pct>=0?'up':'down'],['vega ₹ / pt',inr(i.vega),i.vega>=0?'up':'down'],['theta ₹ / day',inr(i.theta),i.theta>=0?'up':'down'],['day P&L',inr(d.day_pnl),d.day_pnl>=0?'up':'down'],['open P&L',inr(d.pnl),d.pnl>=0?'up':'down'],['worst shock',inr(d.shocks&&d.shocks.worst),'down'],['margin used',m?(m.used_pct!=null?nf(m.used_pct,0)+'%':inr(m.used))+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> · free '+inr(m.available)+'</i>':'connect broker','m']]);
    var br=$('rk-breach'); if(d.breaches&&d.breaches.length){ br.hidden=false; br.innerHTML='<b>LIMIT BREACH</b> '+d.breaches.map(function(b){ return (LIMIT_LABELS[b.key]||b.key)+' '+inr(b.value)+' vs '+inr(b.limit)+' — '+b.note; }).join(' · '); } else { br.hidden=true; }
    $('rk-u').innerHTML=(d.underlyings||[]).map(function(u){ var h=u.hedge; var hs=h?(h.futures_lots?h.futures_side+' '+Math.abs(h.futures_lots)+' fut':'')+(h.atm_option&&h.atm_option_lots?(h.futures_lots?' · or ':'')+h.atm_option+' ×'+Math.abs(h.atm_option_lots):''):'flat'; return '<tr><td style="text-align:left">'+u.u+'<span class="src"> '+(u.sources||[]).join('+')+'</span></td><td>'+nf(u.spot,1)+(u.day_move_pct!=null?' <span class="'+(u.day_move_pct>=0?'up':'down')+'">'+sg(u.day_move_pct,2)+'%</span>':'')+'</td><td>'+u.positions+' · '+u.lots+'</td><td class="'+(u.delta_inr_1pct>=0?'up':'down')+'">'+inr(u.delta_inr_1pct)+'</td><td>'+inr(u.gamma_inr_1pct)+'</td><td>'+inr(u.vega)+'</td><td>'+inr(u.theta)+'</td><td class="hedge">'+(hs||'flat')+'</td></tr>'; }).join('')||'<tr><td colspan="8" style="text-align:left;color:var(--faint)">no open positions — paper a strategy in the builder, run an ALGO, or connect your broker</td></tr>';
    $('rk-e').innerHTML=(d.expiries||[]).map(function(e){ var p=e.payoff||{}; return '<tr><td style="text-align:left">'+e.u+'</td><td>'+(e.expiry?expLabel(e.expiry):'—')+'</td><td>'+(e.dte!=null?nf(e.dte,1)+'d':'—')+'</td><td class="'+(e.delta_inr_1pct>=0?'up':'down')+'">'+inr(e.delta_inr_1pct)+'</td><td>'+inr(e.vega)+'</td><td>'+inr(e.theta)+'</td><td class="down">'+inr(p.max_loss)+'</td><td class="up">'+inr(p.max_profit)+'</td><td>'+((p.breakevens||[]).map(function(b){ return nf(b,0); }).join(' · ')||'—')+'</td></tr>'; }).join('')||'<tr><td colspan="9" style="text-align:left;color:var(--faint)">—</td></tr>';
    var lim=d.limits||{}, bad={}; (d.breaches||[]).forEach(function(b){ bad[b.key]=true; });
    if(!$('rk-limits').children.length||$('rk-limits').getAttribute('data-dirty')!=='1'){ $('rk-limits').innerHTML=Object.keys(LIMIT_LABELS).map(function(k){ return '<label>'+LIMIT_LABELS[k]+'<input type="number" min="0" step="1000" data-k="'+k+'" value="'+(lim[k]||'')+'" class="'+(bad[k]?'bad':'')+'"></label>'; }).join('')+'<button type="button" id="rk-save">SAVE LIMITS</button><span class="msg" id="rk-msg">breaches also show as a red state on the panel header</span>';
      $('rk-save').addEventListener('click',function(){ var body={}; Array.prototype.forEach.call($('rk-limits').querySelectorAll('input'),function(i){ body[i.getAttribute('data-k')]=Number(i.value); }); postJSON('/api/risk',{limits:body},function(){ $('rk-limits').setAttribute('data-dirty','0'); $('rk-msg').textContent='saved'; loadRisk(); },function(e){ $('rk-msg').textContent=e; }); });
      $('rk-limits').addEventListener('input',function(){ $('rk-limits').setAttribute('data-dirty','1'); }); } }
  function drawRisk(){ var d=rk.data, cv=$('rk-cv'); if(!d||!cv||!d.shocks) return; var g=ctx2d(cv), c=g.c, sh=d.shocks, grid=sh.grid[rk.day]||sh.grid['0']; if(!grid) return; var cols=sh.spot_shifts, rows=sh.iv_shifts; var pad={l:58,t:22,r:8,b:6}; var cw=(g.w-pad.l-pad.r)/cols.length, ch=(g.h-pad.t-pad.b)/rows.length; var m=0; rows.forEach(function(_,ri){ cols.forEach(function(_,ci){ m=Math.max(m,Math.abs(grid[ri][ci])); }); }); var worst={v:Infinity,ri:0,ci:0};
    rows.forEach(function(iv,ri){ cols.forEach(function(sp,ci){ var v=grid[ri][ci]; var t=m?v/m:0; var col=t>=0?'rgba(61,214,140,'+(0.12+0.6*t)+')':'rgba(255,92,108,'+(0.12+0.6*(-t))+')'; c.fillStyle=col; c.fillRect(pad.l+ci*cw+1,pad.t+ri*ch+1,cw-2,ch-2); c.fillStyle=C.text; c.textAlign='center'; if(cw>=46||ci%2===0) c.fillText(cw<60?inr(v).replace('₹',''):inr(v),pad.l+ci*cw+cw/2,pad.t+ri*ch+ch/2+4); if(v<worst.v){ worst={v:v,ri:ri,ci:ci}; } }); c.fillStyle=C.faint; c.textAlign='right'; c.fillText('IV '+(iv>=0?'+':'')+iv,pad.l-6,pad.t+ri*ch+ch/2+4); });
    c.fillStyle=C.faint; c.textAlign='center'; cols.forEach(function(sp,ci){ if(cw<46&&ci%2) return; c.fillText((cw<70?'':'spot ')+(sp>=0?'+':'')+sp+'%',pad.l+ci*cw+cw/2,pad.t-7); });
    if(isFinite(worst.v)&&d.positions){ c.strokeStyle=C.gold; c.lineWidth=2; c.strokeRect(pad.l+worst.ci*cw+1,pad.t+worst.ri*ch+1,cw-2,ch-2); c.lineWidth=1; } }
  window.addEventListener('resize',function(){ drawRisk(); drawOi(); });
  if(rkPanel&&!window.FINO_LOCKED){ loadRisk(); setInterval(function(){ if(visible('p-risk')) loadRisk(); },10000); }

  /* ---------- OISCAN ---------- */
  var oi={u:'NIFTY 50',w:'15',data:null,stocks:null}, oiPanel=$('p-oiscan');
  var TAGC={'long build-up':'lb','short build-up':'sb','short covering':'sc','long unwinding':'lu','flat':'flat'};
  function tag(t){ return t?'<span class="tag '+(TAGC[t]||'')+'">'+t.toUpperCase()+'</span>':'—'; }
  segInit($('oi-u'),'data-u',function(u){ oi.u=u; loadOi(); }); segInit($('oi-w'),'data-w',function(w){ oi.w=w; loadOi(); });
  function loadOi(){ if(!oiPanel||window.FINO_LOCKED) return; state('oi-state','loading…'); getJSON('/api/oiscan?u='+encodeURIComponent(oi.u)+'&w='+oi.w,function(d){ oi.data=d; renderOi(d); drawOi(); },function(e){ oi.data=null; state('oi-state',e,'err'); $('oi-read').innerHTML='<b class="quiet">WAITING</b>'+e; $('oi-rows').innerHTML=''; drawOi(); }); }
  function renderOi(d){ var t=new Date(d.ts*1000).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}); state('oi-state','SAMPLED '+t+' · '+d.samples+' TODAY · EXP '+d.expiry,'ok');
    var dsp=d.spot_then?(d.spot-d.spot_then):null;
    kpi($('oi-kpi'),[['spot',nf(d.spot,1)+(dsp!=null?' <i style="font-style:normal;font-size:11px" class="'+(dsp>=0?'up':'down')+'">'+sg(dsp,1)+'</i>':''),'c'],['call OI Δ',sg(d.ce_d,0),d.ce_d>0?'down':'up'],['put OI Δ',sg(d.pe_d,0),d.pe_d>0?'up':'down'],['PCR',nf(d.pcr,2)+(d.pcr_then!=null?' <i style="font-style:normal;font-size:11px;color:var(--muted)">from '+nf(d.pcr_then,2)+'</i>':''),'m'],['call wall',d.walls&&d.walls.call?nf(d.walls.call.strike,0):'—','m'],['put wall',d.walls&&d.walls.put?nf(d.walls.put.strike,0):'—','m'],['window',(d.window==='day'?'since prev close':nf(d.window_actual_min,0)+' min'),'m']]);
    var r=d.read||{}; $('oi-read').innerHTML='<b class="'+r.lean+'">'+(r.lean||'').toUpperCase()+'</b>'+(r.text||'');
    $('oi-rows').innerHTML=(d.top||[]).map(function(x){ return '<tr'+(x.itm?' style="opacity:.75"':'')+'><td>'+nf(x.strike,0)+'</td><td class="'+(x.side==='CE'?'cyan':'')+'" style="color:'+(x.side==='CE'?'var(--cyan)':'var(--pink)')+'">'+x.side+'</td><td>'+nf(x.oi,0)+'</td><td class="'+(x.d_oi>=0?'up':'down')+'">'+sg(x.d_oi,0)+'</td><td class="'+(x.d_px_pct>=0?'up':'down')+'">'+(x.d_px_pct!=null?sg(x.d_px_pct,1)+'%':'—')+'</td><td>'+tag(x.tag)+'</td></tr>'; }).join('')||'<tr><td colspan="6" style="text-align:left;color:var(--faint)">no OI change worth tagging in this window</td></tr>'; }
  function drawOi(){ var cv=$('oi-cv'); if(!cv) return; var g=ctx2d(cv), c=g.c, d=oi.data; if(!d||!d.rows||!d.rows.length){ c.fillStyle=C.faint; c.fillText('OI change by strike appears here once the session has samples',12,24); return; }
    var byK={}; d.rows.forEach(function(r){ var o=byK[r.strike]||(byK[r.strike]={ce:0,pe:0}); o[r.side==='CE'?'ce':'pe']=r.d_oi; }); var ks=Object.keys(byK).map(Number).sort(function(a,b){ return a-b; }); var n=ks.length; var pad={l:52,r:10,t:16,b:22}; var m=1; ks.forEach(function(k){ m=Math.max(m,Math.abs(byK[k].ce),Math.abs(byK[k].pe)); }); var pw=g.w-pad.l-pad.r, ph=g.h-pad.t-pad.b, bw=pw/n, y0=pad.t+ph/2;
    function sx(i){ return pad.l+i*bw; } function sy(v){ return y0-v/m*(ph/2); }
    c.strokeStyle='rgba(190,150,255,.14)'; c.beginPath(); c.moveTo(pad.l,y0); c.lineTo(g.w-pad.r,y0); c.stroke();
    ks.forEach(function(k,i){ var o=byK[k]; c.fillStyle='rgba(127,224,240,.85)'; c.fillRect(sx(i)+bw*.12,Math.min(y0,sy(o.ce)),bw*.34,Math.abs(y0-sy(o.ce))||1); c.fillStyle='rgba(255,110,199,.85)'; c.fillRect(sx(i)+bw*.54,Math.min(y0,sy(o.pe)),bw*.34,Math.abs(y0-sy(o.pe))||1); });
    var spotI=null; ks.forEach(function(k,i){ if(spotI==null&&k>=d.spot) spotI=i; }); if(spotI!=null){ var x=sx(spotI); c.strokeStyle=C.gold; c.setLineDash([4,3]); c.beginPath(); c.moveTo(x,pad.t); c.lineTo(x,g.h-pad.b); c.stroke(); c.setLineDash([]); c.fillStyle=C.gold; c.textAlign='left'; c.fillText('spot '+nf(d.spot,0),x+3,pad.t+8); }
    c.fillStyle=C.faint; c.textAlign='center'; var step=Math.max(1,Math.round(n/8)); ks.forEach(function(k,i){ if(i%step===0) c.fillText(nf(k,0),sx(i)+bw/2,g.h-6); }); c.textAlign='right'; c.fillText(sg(m,0),pad.l-4,pad.t+10); c.fillText(sg(-m,0),pad.l-4,g.h-pad.b-2);
    c.textAlign='left'; c.fillStyle='rgba(127,224,240,.9)'; c.fillText('CALL Δ OI',pad.l+4,pad.t-4); c.fillStyle='rgba(255,110,199,.9)'; c.fillText('PUT Δ OI',pad.l+70,pad.t-4); }
  function loadStocks(){ if(!oiPanel||window.FINO_LOCKED) return; getJSON('/api/oiscan/stocks',function(d){ oi.stocks=d; var rows=(d.rows||[]).slice(0,40); $('oi-stocks').innerHTML=rows.map(function(s){ return '<tr><td style="text-align:left">'+s.sym+'</td><td>'+nf(s.spot,1)+'</td><td class="'+(s.spot_chg_pct>=0?'up':'down')+'">'+(s.spot_chg_pct!=null?sg(s.spot_chg_pct,2)+'%':'—')+'</td><td class="'+(s.d_oi_pct>=0?'up':'down')+'">'+(s.d_oi_pct!=null?sg(s.d_oi_pct,1)+'%':'—')+'</td><td>'+sg(s.ce_d,0)+'</td><td>'+sg(s.pe_d,0)+'</td><td>'+nf(s.pcr,2)+'</td><td>'+tag(s.tag)+'</td></tr>'; }).join('')||'<tr><td colspan="8" style="text-align:left;color:var(--faint)">stock screen fills in ~15 minutes into the session</td></tr>'; if(d.ts) $('oi-snote').textContent=d.count+' stocks · sampled '+new Date(d.ts*1000).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}); },function(){}); }
  /* ---------- HEAT ---------- */
  var ht={u:'fo',mode:'top',size:'move',q:'',data:null}, htPanel=$('p-heat');
  segInit($('ht-u'),'data-u',function(u){ ht.u=u; loadHeat(); }); segInit($('ht-mode'),'data-m',function(m){ ht.mode=m; loadHeat(); }); segInit($('ht-size'),'data-z',function(z){ ht.size=z; drawHeat(); });
  $('ht-q').addEventListener('input',function(e){ ht.q=e.target.value.trim().toUpperCase(); drawHeat(); });
  function heatColor(ch){ var a=Math.min(1,Math.abs(ch)/4); if(ch>0.05) return 'rgb('+Math.round(20+8*a)+','+Math.round(70+120*a)+','+Math.round(50+40*a)+')'; if(ch<-0.05) return 'rgb('+Math.round(110+120*a)+','+Math.round(30+20*a)+','+Math.round(40+20*a)+')'; return 'rgb(58,52,88)'; }
  function loadHeat(){ if(!htPanel||window.FINO_LOCKED) return; getJSON('/api/heat?u='+ht.u+'&mode='+ht.mode+'&n=400',function(d){ ht.data=d; renderHeat(d); drawHeat(); },function(e){ state('ht-state',e,'err'); }); }
  function renderHeat(d){ var names={n50:'NIFTY 50',fo:'F&O STOCKS',all:'ALL NSE'}; var modes={top:'TOP '+d.n+' GAINERS · TOP '+d.n+' LOSERS',all:'ALL '+d.universe+' NAMES',gainers:'ALL GAINERS',losers:'ALL LOSERS'}; $('ht-title').textContent='MARKET HEATMAP · '+names[d.u]+' · '+modes[d.mode]; state('ht-state',(d.open?'MARKET OPEN · LIVE':d.live?'CLOSED · LAST SESSION':'FEED DOWN')+' · '+d.count+' TILES',d.open?'ok':d.live?'':'err');
    var tot=d.adv+d.dec+d.unch||1; kpi($('ht-kpi'),[['advances',d.adv+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+Math.round(100*d.adv/tot)+'%</i>','up'],['declines',d.dec+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+Math.round(100*d.dec/tot)+'%</i>','down'],['unchanged',String(d.unch),'m'],['average move',d.avg!=null?sg(d.avg,2)+'%':'—',d.avg>=0?'up':'down'],['top gainer',d.top?d.top.symbol+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+sg(d.top.change,2)+'%</i>':'—','up'],['top loser',d.bottom?d.bottom.symbol+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+sg(d.bottom.change,2)+'%</i>':'—','down'],['breadth',d.adv+d.dec?(d.adv>d.dec*1.5?'BROAD UP':d.dec>d.adv*1.5?'BROAD DOWN':'MIXED'):'—',d.adv>d.dec*1.5?'up':d.dec>d.adv*1.5?'down':'m']]); }
  function drawHeat(){ var d=ht.data, el=$('ht-map'); if(!d||!el) return; if(!d.rows.length){ el.innerHTML='<div style="color:var(--faint);padding:10px">no quotes yet — the map fills once the feed streams</div>'; return; }
    var maxAbs=Math.max(0.5,Math.max.apply(null,d.rows.map(function(r){ return Math.abs(r.change); }))); var n=d.rows.length; var base=n>300?54:n>150?68:n>60?84:110;
    el.innerHTML=d.rows.map(function(r){ var a=Math.abs(r.change)/maxAbs; var w=ht.size==='move'?Math.round(base*(0.7+0.9*a)):base; var h=ht.size==='move'?Math.round(w*0.62):Math.round(base*0.62); var fs=Math.max(8,Math.min(13,Math.round(w/8))); var dim=ht.q&&r.symbol.indexOf(ht.q)!==0; return '<div class="ht-t'+(dim?' dim':'')+'" style="width:'+w+'px;height:'+h+'px;background:'+heatColor(r.change)+'" data-key="'+r.key+'" data-sym="'+r.symbol+'" title="'+(r.name||r.symbol)+' · ₹'+nf(r.price,2)+' · '+sg(r.change,2)+'%"><b style="font-size:'+fs+'px">'+r.symbol+'</b><i style="font-size:'+Math.max(8,fs-2)+'px">'+sg(r.change,2)+'%</i></div>'; }).join(''); }
  $('ht-map').addEventListener('click',function(e){ var t=e.target.closest('.ht-t'); if(!t) return; var key=t.getAttribute('data-key'); if(window.finoChartTo){ window.finoChartTo(key,t.getAttribute('data-sym')); var cp=$('p-chart'); if(cp&&!cp.hidden){ cp.hidden=false; cp.scrollIntoView({behavior:'smooth',block:'start'}); } } $('ht-note').textContent='charting '+t.getAttribute('data-sym'); });
  if(htPanel&&!window.FINO_LOCKED){ loadHeat(); setInterval(function(){ if(visible('p-heat')&&(!ht.data||ht.data.open||(Date.now()/1000|0)%60<10)) loadHeat(); },10000); }

  /* ---------- STRUCT / SCALPER / SELLER (VIP engines) ---------- */
  var stx={u:'NIFTY 50',tf:'15m',engine:'struct',data:null,layers:{zones:true,liq:true,struct:true,ma:false,st:false,fp:true,vp:true},hover:null,geom:null}, stxPanel=$('p-struct');
  var ENG_NAMES={struct:'STRUCTURE',scalp:'SCALPER',seller:'SELLER'};
  var FOOT={struct:$('stx-foot')?$('stx-foot').textContent:'',
    scalp:'SCALPER: a fast trend engine for 1-minute to 15-minute charts — EMA 9 over 21 (trend), price against the session VWAP (who is in control), Supertrend 7/2 (trailing trend and the stop), RSI 7 momentum, with ADX 14 damping signals when there is no trend. LONG from +0.5, SHORT from −0.5, exit when the score decays or the Supertrend flips; stop = Supertrend line (max 1.5 ATR), target = 1.5R. FOOTPRINT and PROFILE as in STRUCTURE.',
    seller:'SELLER: when to sell premium, which side and where. ADX below 20 = rangebound (sellers favoured), above 28 = stand aside; Bollinger width must be calm but not a coiled squeeze; price mid-range; structure bias picks the side (bullish + discount → sell puts, bearish + premium → sell calls, neutral → straddle); on indices the straddle percentile (premium rich?) and today\'s realised range against the expected move also vote. Suggested strikes come from the range edges, nearest supply/demand and the expected move, rounded to the strike step. Exit on trend or a range break.'};
  function eng(e){ stx.engine=e; Array.prototype.forEach.call($('stx-eng').querySelectorAll('button'),function(b){ b.classList.toggle('on',b.getAttribute('data-e')===e); }); if(e==='scalp'){ stx.layers.ma=true; stx.layers.st=true; stx.layers.zones=false; stx.layers.liq=false; stx.layers.struct=false; } else if(e==='seller'){ stx.layers.ma=false; stx.layers.st=false; stx.layers.zones=true; stx.layers.liq=true; stx.layers.struct=true; } else { stx.layers.ma=false; stx.layers.st=false; stx.layers.zones=true; stx.layers.liq=true; stx.layers.struct=true; } Array.prototype.forEach.call($('stx-layers').querySelectorAll('button'),function(b){ b.classList.toggle('on',!!stx.layers[b.getAttribute('data-l')]); }); $('stx-foot').textContent=FOOT[e]; if(e==='scalp'&&stx.tf==='D'){ stx.tf='5m'; Array.prototype.forEach.call($('stx-tf').querySelectorAll('button'),function(b){ b.classList.toggle('on',b.getAttribute('data-tf')==='5m'); }); } loadStx(); }
  $('stx-eng').addEventListener('click',function(e){ var b=e.target.closest('button'); if(b) eng(b.getAttribute('data-e')); });
  segInit($('stx-u'),'data-u',function(u){ stx.u=u; $('stx-sym').value=''; loadStx(); }); segInit($('stx-tf'),'data-tf',function(tf){ stx.tf=tf; loadStx(); });
  $('stx-layers').addEventListener('click',function(e){ var b=e.target.closest('button'); if(!b) return; var k=b.getAttribute('data-l'); stx.layers[k]=!stx.layers[k]; b.classList.toggle('on',stx.layers[k]); drawStx(); });
  $('stx-sym').addEventListener('keydown',function(e){ if(e.key!=='Enter') return; e.preventDefault(); var v=e.target.value.trim().toUpperCase(); if(!v) return; stx.u='NSE:'+v.replace(/^NSE:/,''); Array.prototype.forEach.call($('stx-u').querySelectorAll('button'),function(x){ x.classList.remove('on'); }); loadStx(); });
  function stxLabel(){ return stx.u.replace('NSE:','').replace(' 50',''); }
  function loadStx(){ if(!stxPanel||window.FINO_LOCKED) return; state('stx-state','loading…'); var cvw=($('stx-cv').getBoundingClientRect().width||900); getJSON('/api/struct?u='+encodeURIComponent(stx.u)+'&tf='+stx.tf+'&engine='+stx.engine+'&bars='+Math.max(80,Math.min(240,Math.floor(cvw/5))),function(d){ stx.data=d; renderStx(d); drawStx(); },function(e){ state('stx-state',e,'err'); }); }
  function renderStx(d){ var dir=d.direction, cls=dir>0?'buy':dir<0?'sell':'neutral'; var word=d.signal; if(stx.engine==='seller'){ cls=dir>0?'buy':dir<0?'sell':'neutral'; }
    $('stx-title').textContent='VIP INDICATOR · '+ENG_NAMES[stx.engine]+' · '+stxLabel()+' '+stx.tf.toUpperCase()+(d.regime?' · '+d.regime.toUpperCase():''); state('stx-state',(d.stats?'HIT '+nf(d.stats.hit_rate,0)+'% OF '+d.stats.n+' · ':'')+d.bars+' BARS',dir>0?'ok':dir<0?'err':'');
    var pos=((d.score+1)/2*100).toFixed(1); var since=d.since?(' · '+(d.since.label||d.since.side)+' since '+new Date(d.since.t).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})+(stx.tf!=='D'?' '+new Date(d.since.t).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}):'')+' @ '+nf(d.since.price,1)):'';
    var confTxt=stx.engine==='struct'?d.confluence:stx.engine==='scalp'?(d.regime==='trending'?'TREND OK':'NO TREND'):(d.regime||'').toUpperCase(); var confCls=stx.engine==='struct'?(d.confluence==='CONFLUENCE'?'ok':d.confluence==='CONFLICT'?'bad':'mid'):(dir>0?'ok':dir<0?'bad':'mid');
    var lo=stx.engine==='seller'?'STAND ASIDE':'STRONG SELL', hi=stx.engine==='seller'?'SELL PREMIUM':'STRONG BUY';
    $('stx-sig').innerHTML='<div class="lbl '+cls+'">'+word+'</div><div><div class="meter"><b class="l">'+lo+'</b><b class="m">0</b><b class="r">'+hi+'</b><i style="left:'+pos+'%"></i></div><div class="sub">score <b>'+(d.score>=0?'+':'')+nf(d.score,2)+'</b>'+(stx.engine==='struct'?' · price action <b>'+(d.pa_score>=0?'+':'')+nf(d.pa_score,2)+'</b> · classic <b>'+(d.classic_score>=0?'+':'')+nf(d.classic_score,2)+'</b>':'')+since+'</div></div><div class="conf '+confCls+'">'+confTxt+'</div>';
    var items;
    if(d.kpis){ items=d.kpis.map(function(k){ return [k[0],k[1],k[2]]; }); }
    else { var s=d.summary||{}, ev=s.last_event; items=[['structure',(s.structure_word||'—').toUpperCase()+(ev?'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+ev.type+' '+(ev.dir>0?'up':'down')+' @ '+nf(ev.level,0)+' · '+ev.bars_ago+' bars ago</i>':''),s.structure===1?'up':s.structure===-1?'down':'m'],['last',nf(d.entry,1),'c'],['dealing range',s.range?nf(s.range.lo,0)+'–'+nf(s.range.hi,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+nf(s.range.pos_pct,0)+'% · '+s.range.zone+'</i>':'—',s.range&&s.range.zone==='discount'?'up':s.range?'down':'m'],['nearest demand',s.nearest_demand!=null?nf(s.nearest_demand,0):'—','up'],['nearest supply',s.nearest_supply!=null?nf(s.nearest_supply,0):'—','down'],['liquidity',(s.liquidity_above!=null?'▲ '+nf(s.liquidity_above,0):'')+(s.liquidity_below!=null?(s.liquidity_above!=null?' · ':'')+'▼ '+nf(s.liquidity_below,0):'')||'—','m'],['stop / target',d.stop?nf(d.stop,0)+' / '+nf(d.target,0):'—','m'],['past flips hit',d.stats?nf(d.stats.hit_rate,0)+'% of '+d.stats.n:'—',d.stats&&d.stats.hit_rate>=50?'up':'m']]; }
    if(d.profile){ items.push(['POC · value area',nf(d.profile.poc,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+nf(d.profile.val,0)+'–'+nf(d.profile.vah,0)+'</i>','c']); }
    if(d.fp&&d.fp.has_volume&&d.fp.cvd.length){ var last=d.fp.rows[d.fp.rows.length-1]; items.push(['bar delta · CVD',sg(last[5],0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> · '+sg(d.fp.cvd[d.fp.cvd.length-1],0)+'</i>',last[5]>=0?'up':'down']); }
    kpi($('stx-kpi'),items);
    function tbl(group){ return '<table>'+(d.systems||[]).filter(function(x){ return x.group===group; }).map(function(x){ return '<tr><td class="v '+(x.vote>0?'up':x.vote<0?'down':'z')+'">'+(x.vote>0?(stx.engine==='seller'?'SELL OK':'BUY'):x.vote<0?(stx.engine==='seller'?'NO':'SELL'):'—')+'</td><td class="n">'+x.name+'<small>'+x.who+'</small></td><td class="note">'+x.note+'</td></tr>'; }).join('')+'</table>'; }
    if(stx.engine==='struct'){ $('stx-sys').innerHTML='<div><h5>Price action · smart money<i>'+(d.pa_score>=0?'+':'')+nf(d.pa_score,2)+'</i></h5>'+tbl('price action')+'</div><div><h5>Classic systems<i>'+(d.classic_score>=0?'+':'')+nf(d.classic_score,2)+'</i></h5>'+tbl('classic')+'</div>'; }
    else { var grp=stx.engine==='scalp'?'scalper':'seller'; $('stx-sys').innerHTML='<div style="grid-column:1/-1"><h5>'+ENG_NAMES[stx.engine]+' · what each rule says<i>'+(d.score>=0?'+':'')+nf(d.score,2)+'</i></h5>'+tbl(grp)+'</div>'; } }
  function drawStx(){ if(!window.finoPA) return; var r=window.finoPA.draw($('stx-cv'),stx.data,{layers:stx.layers,tf:stx.tf,hover:stx.hover}); if(!r) return; stx.geom=r.geom; if(r.hoverText) $('stx-note').textContent=r.hoverText; }
  $('stx-cv').addEventListener('pointermove',function(e){ if(!stx.geom) return; var r=e.currentTarget.getBoundingClientRect(); var i=Math.floor((e.clientX-r.left-stx.geom.pad.l)/stx.geom.bw); if(i!==stx.hover){ stx.hover=i; drawStx(); } });
  $('stx-cv').addEventListener('pointerleave',function(){ stx.hover=null; drawStx(); $('stx-note').textContent='move the pointer over the chart to read a bar'; });
  if(window.FINO_PINE&&$('stx-pine')) $('stx-pine').hidden=false;
  if(stxPanel&&!window.FINO_LOCKED){ loadStx(); setInterval(function(){ if(visible('p-struct')) loadStx(); },60000); }
  window.addEventListener('resize',function(){ drawStx(); });

  /* ---------- IVP ---------- */
  var ivp={u:'NIFTY 50',data:null,poll:null}, ivpPanel=$('p-ivp');
  segInit($('ivp-u'),'data-u',function(u){ ivp.u=u; ivp.data=null; loadIvp(); });
  function loadIvp(){ if(!ivpPanel||window.FINO_LOCKED) return; if(ivp.poll) clearTimeout(ivp.poll); getJSON('/api/strdhist?u='+encodeURIComponent(ivp.u)+'&n=20',function(d){ if(d.status==='running'){ state('ivp-state','building '+Math.round((d.progress||0)*100)+'% · '+d.dte+' DTE'); $('ivp-note').textContent='fetching past cycles from the archive — a minute on first use'; ivp.poll=setTimeout(loadIvp,2000); return; } if(d.status==='error'){ state('ivp-state',d.error||'failed','err'); return; } ivp.data=d; renderIvp(d); drawIvp(); },function(e){ state('ivp-state',e,'err'); }); }
  function renderIvp(d){ var n=d.now||{}, v=d.vix; state('ivp-state',(d.live?'LIVE':'LAST')+' · EXP '+d.expiry+' · '+d.dte+' DTE · '+d.n+' CYCLES','ok'); $('ivp-note').textContent=n.read||(d.today&&d.today.points&&d.today.points.length?'':'today\'s straddle path appears once the session has candles');
    kpi($('ivp-kpi'),[['straddle now',n.straddle!=null?'₹'+nf(n.straddle,1)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+nf(n.pct,2)+'% of spot</i>':'—','c'],['straddle percentile',n.pct_percentile!=null?nf(n.pct_percentile,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> vs '+n.cycles+' cycles</i>':'—',n.pct_percentile>=75?'down':n.pct_percentile<=25?'up':'m'],['median at this time',n.pct_median!=null?nf(n.pct_median,2)+'%<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+nf(n.pct_min,2)+'–'+nf(n.pct_max,2)+'</i>':'—','m'],['ATM IV now',n.iv!=null?nf(n.iv,1)+'%':'—','c'],['IV percentile',n.iv_percentile!=null?nf(n.iv_percentile,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> median '+nf(n.iv_median,1)+'%</i>':'—',n.iv_percentile>=75?'down':n.iv_percentile<=25?'up':'m'],['India VIX',v?nf(v.last,2)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> rank '+nf(v.rank,0)+' · pct '+nf(v.percentile,0)+' · 1y '+nf(v.low,1)+'–'+nf(v.high,1)+'</i>':'—',v&&v.rank>=70?'down':v&&v.rank<=30?'up':'m']]);
    $('ivp-rows').innerHTML=(d.samples||[]).slice(0,12).map(function(s){ return '<tr><td>'+s.expiry.slice(5)+'</td><td>'+s.day.slice(5)+'</td><td>'+nf(s.atm,0)+'</td><td>'+nf(s.open_pct,2)+'%</td><td>'+nf(s.close_pct,2)+'%</td><td class="'+(s.decay_pct<0?'down':'up')+'">'+(s.decay_pct!=null?sg(s.decay_pct,0)+'%':'—')+'</td></tr>'; }).join('')||'<tr><td colspan="6" style="text-align:left;color:var(--faint)">no past cycles could be built for this DTE</td></tr>'; }
  function drawIvp(){ var d=ivp.data, cv=$('ivp-cv'); if(!d||!cv) return; var g=ctx2d(cv), c=g.c; var MIN=[]; for(var h=9;h<16;h++) for(var m=0;m<60;m+=5){ var t=(h<10?'0':'')+h+':'+(m<10?'0':'')+m; if(t>='09:15'&&t<='15:30') MIN.push(t); } var xi={}; MIN.forEach(function(t,i){ xi[t]=i; }); var N=MIN.length; var pad={l:46,r:10,t:12,b:20}; var pw=g.w-pad.l-pad.r, ph=g.h-pad.t-pad.b;
    var lo=Infinity, hi=-Infinity; (d.bands||[]).forEach(function(b){ lo=Math.min(lo,b[1]); hi=Math.max(hi,b[3]); }); ((d.today||{}).points||[]).forEach(function(p){ lo=Math.min(lo,p[2]); hi=Math.max(hi,p[2]); }); if(!isFinite(lo)){ c.fillStyle=C.faint; c.fillText('no cycles to draw',pad.l+6,pad.t+24); return; } var mg=(hi-lo)*.08||0.1; lo-=mg; hi+=mg;
    function sx(t){ return pad.l+(xi[t]||0)/(N-1)*pw; } function sy(v){ return pad.t+(hi-v)/(hi-lo)*ph; }
    if(d.bands&&d.bands.length){ c.fillStyle='rgba(106,53,240,.16)'; c.beginPath(); d.bands.forEach(function(b,i){ i===0?c.moveTo(sx(b[0]),sy(b[3])):c.lineTo(sx(b[0]),sy(b[3])); }); d.bands.slice().reverse().forEach(function(b){ c.lineTo(sx(b[0]),sy(b[1])); }); c.closePath(); c.fill(); }
    (d.samples||[]).forEach(function(s){ c.strokeStyle='rgba(170,140,255,.25)'; c.beginPath(); s.points.forEach(function(p,i){ i===0?c.moveTo(sx(p[0]),sy(p[2])):c.lineTo(sx(p[0]),sy(p[2])); }); c.stroke(); });
    if(d.bands&&d.bands.length){ c.strokeStyle=C.gold; c.setLineDash([5,4]); c.lineWidth=1.4; c.beginPath(); d.bands.forEach(function(b,i){ i===0?c.moveTo(sx(b[0]),sy(b[2])):c.lineTo(sx(b[0]),sy(b[2])); }); c.stroke(); c.setLineDash([]); c.lineWidth=1; }
    var tp=(d.today||{}).points||[]; if(tp.length){ c.strokeStyle=C.cyan; c.lineWidth=2; c.beginPath(); tp.forEach(function(p,i){ i===0?c.moveTo(sx(p[0]),sy(p[2])):c.lineTo(sx(p[0]),sy(p[2])); }); c.stroke(); c.lineWidth=1; var l=tp[tp.length-1]; c.fillStyle=C.cyan; c.beginPath(); c.arc(sx(l[0]),sy(l[2]),3,0,Math.PI*2); c.fill(); c.textAlign='left'; c.fillText(nf(l[2],2)+'%',Math.min(sx(l[0])+6,g.w-pad.r-44),sy(l[2])+4); }
    c.fillStyle=C.faint; c.textAlign='right'; for(var i=0;i<=4;i++){ var v=lo+(hi-lo)*i/4; c.fillText(nf(v,2)+'%',pad.l-4,sy(v)+3); } c.textAlign='center'; ['09:15','10:30','11:45','13:00','14:15','15:30'].forEach(function(t){ c.fillText(t,sx(t),g.h-6); });
    c.textAlign='left'; c.fillStyle=C.cyan; c.fillText('TODAY',pad.l+4,pad.t-2); c.fillStyle=C.gold; c.fillText('MEDIAN',pad.l+52,pad.t-2); c.fillStyle='rgba(170,140,255,.9)'; c.fillText('PAST CYCLES',pad.l+110,pad.t-2); }
  if(ivpPanel&&!window.FINO_LOCKED){ loadIvp(); setInterval(function(){ if(visible('p-ivp')&&ivp.data) loadIvp(); },60000); }
  window.addEventListener('resize',function(){ drawIvp(); });

  /* ---------- MOVE ---------- */
  var mv={u:'NIFTY 50',data:null}, mvPanel=$('p-move');
  segInit($('mv-u'),'data-u',function(u){ mv.u=u; loadMove(); });
  function loadMove(){ if(!mvPanel||window.FINO_LOCKED) return; getJSON('/api/move?u='+encodeURIComponent(mv.u),function(d){ mv.data=d; renderMove(d); drawMove(); },function(e){ state('mv-state',e,'err'); }); }
  function renderMove(d){ var e=d.expected||{}, r=d.realised||{}, c=d.compare||{}; state('mv-state',(d.live?'LIVE':'LAST')+' · ATM '+nf(d.atm,0)+' · IV '+nf(e.iv,1)+'%','ok'); $('mv-note').textContent=c.verdict||(r.bars?'':'no candles for today yet');
    var pct=function(x){ return x!=null?nf(100*x/e.spot,2)+'%':'—'; };
    kpi($('mv-kpi'),[['expected day ±',e.em_day!=null?nf(e.em_day,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+pct(e.em_day)+'</i>':'—','c'],['realised range',r.range!=null?nf(r.range,0)+(c.range_vs_expected_pct!=null?'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+nf(c.range_vs_expected_pct,0)+'% of exp</i>':''):'—',c.range_vs_expected_pct>110?'down':c.range_vs_expected_pct<60?'m':'up'],['move vs prev close',r.move!=null?sg(r.move,0)+(c.move_sigmas!=null?'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+nf(c.move_sigmas,2)+'σ</i>':''):'—',r.move>=0?'up':'down'],['expected week ±',e.em_week!=null?nf(e.em_week,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> '+pct(e.em_week)+'</i>':'—','m'],['straddle → expiry',e.em_expiry_straddle!=null?'₹'+nf(e.em_expiry_straddle,0)+'<i style="font-style:normal;font-size:10px;color:var(--muted)"> 1σ '+nf(e.sigma_expiry_straddle,0)+' · '+nf(e.t_days,1)+'d</i>':'—','m'],['band touched',c.touched_upper?'UPPER':c.touched_lower?'LOWER':(r.bars?'none':'—'),c.touched_upper||c.touched_lower?'down':'up']]); }
  function drawMove(){ var d=mv.data, cv=$('mv-cv'); if(!d||!cv) return; var g=ctx2d(cv), c=g.c, e=d.expected||{}, r=d.realised||{}; var pc=r.prev_close||e.spot, em=e.em_day||0; var path=r.path||[]; var pad={l:56,r:10,t:12,b:20}; var pw=g.w-pad.l-pad.r, ph=g.h-pad.t-pad.b;
    var lo=pc-em*1.6, hi=pc+em*1.6; path.forEach(function(p){ lo=Math.min(lo,p[1]); hi=Math.max(hi,p[1]); }); var mg=(hi-lo)*.06||1; lo-=mg; hi+=mg; var N=75; function sx(i){ return pad.l+i/(N-1)*pw; } function sy(v){ return pad.t+(hi-v)/(hi-lo)*ph; }
    if(em){ c.fillStyle='rgba(61,214,140,.08)'; c.fillRect(pad.l,sy(pc+em),pw,sy(pc)-sy(pc+em)); c.fillStyle='rgba(255,92,108,.08)'; c.fillRect(pad.l,sy(pc),pw,sy(pc-em)-sy(pc)); c.strokeStyle='rgba(245,200,66,.55)'; c.setLineDash([4,3]); c.beginPath(); c.moveTo(pad.l,sy(pc+em)); c.lineTo(g.w-pad.r,sy(pc+em)); c.moveTo(pad.l,sy(pc-em)); c.lineTo(g.w-pad.r,sy(pc-em)); c.stroke(); c.setLineDash([]); c.fillStyle=C.gold; c.textAlign='left'; c.fillText('+1σ '+nf(pc+em,0),pad.l+4,sy(pc+em)-3); c.fillText('−1σ '+nf(pc-em,0),pad.l+4,sy(pc-em)+11); }
    c.strokeStyle='rgba(255,255,255,.25)'; c.setLineDash([2,3]); c.beginPath(); c.moveTo(pad.l,sy(pc)); c.lineTo(g.w-pad.r,sy(pc)); c.stroke(); c.setLineDash([]); c.fillStyle=C.faint; c.textAlign='right'; c.fillText('prev '+nf(pc,0),pad.l-4,sy(pc)+3); c.fillText(nf(hi,0),pad.l-4,pad.t+8); c.fillText(nf(lo,0),pad.l-4,g.h-pad.b-2);
    if(path.length){ c.strokeStyle=C.cyan; c.lineWidth=1.6; c.beginPath(); path.forEach(function(p,i){ if(i===0) c.moveTo(sx(i),sy(p[1])); else c.lineTo(sx(i),sy(p[1])); }); c.stroke(); c.lineWidth=1; var last=path[path.length-1]; c.fillStyle=C.cyan; c.beginPath(); c.arc(sx(path.length-1),sy(last[1]),3,0,Math.PI*2); c.fill(); c.textAlign='left'; c.fillText(nf(last[1],0),Math.min(sx(path.length-1)+6,g.w-pad.r-40),sy(last[1])+4); if(r.high!=null){ c.strokeStyle='rgba(61,214,140,.5)'; c.beginPath(); c.moveTo(pad.l,sy(r.high)); c.lineTo(g.w-pad.r,sy(r.high)); c.stroke(); c.strokeStyle='rgba(255,92,108,.5)'; c.beginPath(); c.moveTo(pad.l,sy(r.low)); c.lineTo(g.w-pad.r,sy(r.low)); c.stroke(); } } else { c.fillStyle=C.faint; c.textAlign='left'; c.fillText("today's path appears once the session has candles",pad.l+6,pad.t+24); }
    c.fillStyle=C.faint; c.textAlign='center'; ['09:15','10:30','11:45','13:00','14:15','15:30'].forEach(function(t,i){ c.fillText(t,sx(Math.min(i*15,74)),g.h-6); }); }
  if(mvPanel&&!window.FINO_LOCKED){ loadMove(); setInterval(function(){ if(visible('p-move')) loadMove(); },30000); }
  window.addEventListener('resize',function(){ drawMove(); });

  if(oiPanel&&!window.FINO_LOCKED){ loadOi(); loadStocks(); setInterval(function(){ if(visible('p-oiscan')) loadOi(); },60000); setInterval(function(){ if(visible('p-oiscan')) loadStocks(); },300000); }
})();
"""
